#!/usr/bin/env python3
"""
Fetch Bring Me Hope's Steam announcements and write docs/game-versions.md.

Pulls the public Steam news feed (no API key required) for the app and renders a
table of updates, each linking to its Steam news post. Designed to run in CI
just before `mkdocs build` so the page stays current, and is safe to run locally.

If the fetch fails, an existing docs/game-versions.md is left untouched, so a
transient Steam outage never blanks the page.
"""

from __future__ import annotations

import json
import re
import sys
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

APP_ID = 1493290
NEWS_URL = (
    "https://api.steampowered.com/ISteamNews/GetNewsForApp/v2/"
    f"?appid={APP_ID}&count=100&format=json"
)
STORE_NEWS = f"https://store.steampowered.com/news/app/{APP_ID}/view/"
STORE_PAGE = f"https://store.steampowered.com/app/{APP_ID}/Bring_Me_Hope/"
OUT = Path(__file__).resolve().parent.parent / "docs" / "game-versions.md"

VERSION_RE = re.compile(r"(\d+\.\d+(?:\.\d+){0,2})")


def fetch_items() -> list[dict]:
    req = urllib.request.Request(NEWS_URL, headers={"User-Agent": "BMHWiki/1.0"})
    with urllib.request.urlopen(req, timeout=30) as resp:
        data = json.load(resp)
    return data.get("appnews", {}).get("newsitems", [])


def render(items: list[dict]) -> str:
    rows = []
    for it in sorted(items, key=lambda i: i.get("date", 0), reverse=True):
        title = (it.get("title") or "").strip()
        gid = it.get("gid", "")
        url = STORE_NEWS + str(gid) if gid else (it.get("url") or "")
        date = datetime.fromtimestamp(
            it.get("date", 0), tz=timezone.utc
        ).strftime("%Y-%m-%d")
        m = VERSION_RE.search(title)
        version = m.group(1) if m else ""
        safe_title = title.replace("|", "\\|")
        link = f"[{safe_title}]({url})" if url else safe_title
        rows.append(f"| {version} | {link} | {date} |")

    body = [
        "<!-- Generated by tools/fetch_steam_news.py from the Steam news feed. -->",
        "",
        "# Game versions",
        "",
        "Update history for *Bring Me Hope*, pulled from the game's "
        f"[Steam announcements]({STORE_PAGE}). Each entry links to its full patch "
        "notes on Steam. This page refreshes automatically.",
        "",
    ]
    if rows:
        body += ["| Version | Update | Date |", "|---|---|---|", *rows]
    else:
        body += ["_No update posts yet. Check back after the next Steam announcement._"]
    body.append("")
    return "\n".join(body)


def main() -> None:
    try:
        items = fetch_items()
    except Exception as e:  # network error, bad response, etc.
        print(f"steam news fetch failed: {e}", file=sys.stderr)
        if OUT.exists():
            print("keeping existing game-versions.md")
            return
        items = []
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(render(items), encoding="utf-8")
    print(f"wrote {OUT.name} with {len(items)} update(s)")


if __name__ == "__main__":
    main()
